#!/bin/bash
set +h
set -e

cd $PKGDIR
patch -Np1 -i ../bash-4.2-fixes-11.patch
./configure --prefix=/tools --without-bash-malloc
make
make install
ln -sv bash /tools/bin/sh
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
