#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr --enable-cxx
make
make -k check 2>&1 | tee gmp-check-log >> $TEST_LOG 2>&1 || true
awk '/tests passed/{total+=$2} ; END{print total}' gmp-check-log >> $TEST_LOG 2>&1
make install
mkdir -v /usr/share/doc/gmp-5.1.1
cp    -v doc/{isa_abi_headache,configuration} doc/*.html \
         /usr/share/doc/gmp-5.1.1
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
