#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure  --prefix=/usr        \
             --enable-thread-safe \
             --docdir=/usr/share/doc/mpfr-3.1.1
make
make -k check >> $TEST_LOG 2>&1 || true
make html

make install
make install-html
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
