#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr
echo '#define YYENABLE_NLS 1' >> lib/config.h
make
make -k check >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
