#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -i -e '/gets is a/d' lib/stdio.in.h
./configure --prefix=/usr
make
make -k check >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
