#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr --libexecdir=/usr/lib
make
make -k check >> $TEST_LOG 2>&1 || true
make install
mkdir -v /usr/share/doc/gawk-4.0.2
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-4.0.2
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
