#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr       \
            --bindir=/bin       \
            --libdir=/lib       \
            --sysconfdir=/etc   \
            --disable-manpages  \
            --with-xz           \
            --with-zlib
make
make -k check >> $TEST_LOG 2>&1 || true
make pkgconfigdir=/usr/lib/pkgconfig install

for target in depmod insmod modinfo modprobe rmmod; do
  ln -sv ../bin/kmod /sbin/$target
done

ln -sv kmod /bin/lsmod
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
